language: python

python:
  - '3.5'
  - '3.5-dev' # 3.5 development branch
  - '3.6-dev' # 3.6 development branch
  - 'nightly' # currently points to 3.7-dev

git:
  depth: 3

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%f --no-merges -n 1)\""

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install

script:
  - coverage run --source=vulk setup.py test
  - flake8 vulk
  - pylint --rcfile=.pylintrc-travis vulk

after_success:
  - coveralls

deploy:
  provider: script
  script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis_deploy.sh; fi'
  on:
    python: '3.5'

matrix:
  allow_failures:
    - python: '3.5-dev'
    - python: '3.6-dev'
    - python: 'nightly'
