language: python

python:
  - '3.5'

git:
  depth: 3

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
#- py.test .
  - flake8 vulk
#- pylint vulk

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./apigenerator/travis_deploy.sh; fi'

env:
  global:
    - secure: CYIiBvjFqSYgMaWpyhSUByVb73JIcYwwKEQQxUPlszGi7qGBvylOcRtk+3IYGlx3AVsEm/EEYtQ45fHNJlbc2pHsLJ3h5SdPIMyiUY/HkNLwrOZMZr0xbvwhbeHwXx4+B7j/8MSi1H7dgl357UjQujAngamTN8Bxc7v10nl+n03aSCDkuXxEtJRk0q4giHjy7i+CD4vr/fw+GGZoUaZoRA4nxkQ2MsbguRXiwtP4mvW19empd8SpNccq8NOKVpqEOW9BhU8oBB667xarYKNJ+87R3/mIDtt7oWWcSA0qlD0l8CXvFk/ILiqFdA+gvxUyAOcgEEC7Y9OfjSKlnomS4dk7u8HxdPl2gCTaQobwWK1nPif8Gy/AfIalOwElly74f8vqSw8K5hE0qGf0RoYJzAJTtygKGsnglAAGKG/GD2c/25yDLXhtcRkFa8Hwdc8tfQuYrrPtcbPRKjkQcgKOzSYczcMa+c6lWLr5BSWjuJNIIKgSKOP/gxSoe7sjoX9kEMd16mljZbosyBt8hkbEAqA/4kDSH+M+jKs/QY9ndRSOCi+LqNMZFiC0LifwFykjE3qvSj7rrDcJGDGAv8T6mAEF/78gaS6L/6CmOdICgyucsuoADhjVc2HkgOjBOUuRvXzblsmBUCT9L6MKdJbg/fY0DkLQ2LvHNSsl8YKv0Iw=
    - secure: KcoQX/kO3FXcjFlLUW2VCbLNTFBtwPV8kjSwwQiKC+7JjyamcXjIq/17qcUdT7rxuhCJExnAFzJQDhzbdAZYw/oKN4We0kU2Ll3D9P4IHoh2XlwgrP2D6MOX5bpXXaCr7pB/LxwRjV5TvX6fQ77lTi0tYaNZZTt4yHgzRQktJf4uYbb3R/ZA73zk/23uFPm5QeYVGGaZybB16mb3qzJrgKdbdb1vsbcCy3hyZZ8GifsvGlJevOKjT6BJUihJr6JgEcWFMQ4fGzjRmujS2MrcYSrJZauchu9SPjwb/VEzFnFDQ9DNyoiW5bKM7sIK+WuvRv8Ye2HAJrYIE7cuDfHamMjG832VDx5JKMHvskevd31ZvcbRaULCIKC57Fx+UOvHeBghX3/Hev9TcV7xUlip6h+Azt3EmevHOnzsxrsvHraPQ+78okEjm2DuYGYvXqa5Aixesu1kLFf6QrzQCGP6S7Y8MKWil2XLw/ZDtPgjTJcrzLn1ikEqty4Sx0HlYQ++Fi4BJ6W0eCJSaBbI5rH1fw2OhIG6v6Ssn2lsXXta0rD8bsYb+3lTR+cnpfjTRJhbMAmNkvfcDCrT46rYSifRdciuNHf1Rl6PQ8zO5wLlkMM0iczq45MKH/O1pJCqI9s19mQl1Uv/hUzrvgoX9JlHNgIgGJn6pdmb6C3l8vWX7PQ=
